### ISSUE TITLE
Please support custom headers

### ISSUE THREAD

**Issue by satai** [micronaut-projects/micronaut-email#90]
Please support custom headers.

(I need `List-Unsubscribe` for our project, but more general support makes sense for custom headers. In principle any valid header name should work, with exception of headers that already have custom handling in the codebase.)

**Comment by sdelamo** [comment]
The API already contains methods which take a `Consumer` so that you can set headers or any other custom field. 

https://micronaut-projects.github.io/micronaut-email/latest/api/io/micronaut/email/EmailSender.html#send-io.micronaut.email.Email.Builder-java.util.function.Consumer-

You can already do: 

```java
email.send(emailBuilder, message -> {
 for (Map.Entry<String, List<String>> entry : headers.entrySet()) {
                 for (String value : entry.getValue()) {
                     message.addHeader(entry.getKey(), value);
                 }
             }
})
```

We are going to improve the docs [#93](https://github.com/micronaut-projects/micronaut-email/issues/93)
